fix outputs.skip_klio_existence_check with pipeline without inputs
With the following job_config : 

```yaml
  data:
    outputs:
      - type: gcs
        location: gs://data-usc1-audio-stg/audio-tmp-delete-me-pls
        file_suffix: .wav
        skip_klio_existence_check: False
```
we get this error :
```
NotImplementedError: Unable to extract PValue inputs from (None, <PCollection[Output Force Filter/ParDo(KlioFilterForce).pass_thru] at 0x7f5e228f5cf8>); either <Flatten(PTransform) label=[Flatten to Pass Thru]> does not accept inputs of this format, or it does not properly override _extract_input_pvalues
```

This pr fix the issue by not using the flatten step when pass_thru is None.